name: Deploy to GitHub Pages

on:
  push:
    # Triggers the workflow on push events to either main or master
    branches: ['main', 'master']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}allinone/
    runs-on: ubuntu-latest
    defaults:
      run:
        # Specify the sub-folder where your Vite app lives
        working-directory: ./allinone
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Prepare folder structure
        run: |
          mkdir -p deploy_folder/allinone
          cp -r dist/* deploy_folder/allinone/
          touch deploy_folder/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          #  Point to the newly created deployment folder
          path: './allinone/deploy_folder'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4